[cerebrium.deployment]
name = "mtailor-classification-model"
python_version = "3.12"
include = [
    "main.py",
    "src/**/*",
    "scripts/**/*",
    "models/model.onnx",
    "requirements.txt",
    "Dockerfile"
]

[cerebrium.hardware]
cpu = 1
memory = 1.0
compute = "CPU"
gpu_count = 0
provider = "aws"
region = "us-east-1"

[cerebrium.runtime.custom]
port = 8192
healthcheck_endpoint = "/health"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 1
replica_concurrency = 100
